apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
replicas:
- count: 8
  name: vote
resources:
- ../base
patches:
- path: deployment.yaml
- path: service.yaml
images: 
- name: schoolofdevops/vote
  newTag: v4
namespace: instavote
commonLabels:
  project: instavote
  env: staging
commonAnnotations:
   supported-by: example@my_example.com
